Catch "Throwable" instead of "Exception", because the Class.forName seems to be throwing a NoClassDefFoundError instead of a ClassNotFoundException.
git-svn-id: https://svn.code.sf.net/p/processdash/code/trunk@1497 560cad82-bde2-470f-af40-e4e1f8d6548a